apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: websockets

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: mqtt
      nodePort: 30000
      name: mqtt
    - port: 9001
      targetPort: websockets
      nodePort: 30001
      name: websockets
  selector:
    app: mosquitto